#!/usr/bin/env node
/**
 * OpenFang Daemon Manager
 *
 * Runs alongside Vite dev server via `npm run dev`.
 * - Finds the OpenFang binary (./bin/, PATH, or /tmp/openfang build output)
 * - Creates ~/.openfang/config.toml using the project's ANTHROPIC_API_KEY
 * - Starts the daemon with `openfang start`
 * - Restarts on crash
 * - Exposes a status API on port 3001 for the Agentis UI
 */

import { spawn, execSync } from 'child_process'
import { existsSync, mkdirSync, createWriteStream, chmodSync, statSync, unlinkSync, writeFileSync, readFileSync } from 'fs'
import { get as httpsGet } from 'https'
import { createServer } from 'http'
import path from 'path'
import { fileURLToPath } from 'url'
import os from 'os'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const ROOT      = path.resolve(__dirname, '..')

// ── Load .env / .env.local into process.env ──────────────────────────────────
for (const envFile of ['.env', '.env.local']) {
  const envPath = path.join(ROOT, envFile)
  if (existsSync(envPath)) {
    try {
      readFileSync(envPath, 'utf8').split('\n').forEach(line => {
        line = line.trim()
        if (!line || line.startsWith('#')) return
        const idx = line.indexOf('=')
        if (idx < 0) return
        const key = line.slice(0, idx).trim()
        const val = line.slice(idx + 1).trim().replace(/^["']|["']$/g, '')
        if (key && !process.env[key]) process.env[key] = val
      })
    } catch { /* ignore */ }
  }
}

const BIN_DIR  = path.join(ROOT, 'bin')
const IS_WIN   = process.platform === 'win32'
const IS_MAC   = process.platform === 'darwin'
const IS_ARM   = process.arch === 'arm64'
const BIN_NAME = IS_WIN ? 'openfang.exe' : 'openfang'
const BIN_PATH = path.join(BIN_DIR, BIN_NAME)

// Build output from cloned repo (used by the one-time build step)
const BUILD_OUT = '/tmp/openfang/target/release/openfang'

const OPENFANG_PORT  = parseInt(process.env.VITE_OPENFANG_PORT  ?? '4200', 10)
const MANAGER_PORT   = parseInt(process.env.OPENFANG_MANAGER_PORT ?? '3001', 10)

// ── Status ────────────────────────────────────────────────────────────────────
let status = { state: 'idle', message: 'Initialising…', port: OPENFANG_PORT }

function setStatus(state, message) {
  status = { state, message, port: OPENFANG_PORT, binPath: BIN_PATH }
  console.log(`[OpenFang] ${message}`)
}

// ── Find binary ───────────────────────────────────────────────────────────────

function findInPath() {
  try {
    const r = execSync(IS_WIN ? 'where openfang' : 'which openfang', { encoding: 'utf8', stdio: 'pipe' })
    return r.trim().split('\n')[0].trim() || null
  } catch { return null }
}

function isValidBinary(p) {
  try {
    const st = statSync(p)
    if (st.size < 1024 * 10) return false  // < 10KB is definitely not a real binary
    if (!IS_WIN) chmodSync(p, 0o755)
    return true
  } catch { return false }
}

// ── Auto-setup ~/.openfang/config.toml ───────────────────────────────────────

function ensureConfig() {
  const configDir  = path.join(os.homedir(), '.openfang')
  const configPath = path.join(configDir, 'config.toml')
  if (existsSync(configPath)) return

  mkdirSync(configDir, { recursive: true })
  writeFileSync(configPath, `# OpenFang config — auto-generated by Agentis
api_listen = "127.0.0.1:${OPENFANG_PORT}"

[default_model]
provider = "anthropic"
model    = "claude-sonnet-4-20250514"
api_key_env = "ANTHROPIC_API_KEY"

[memory]
decay_rate = 0.05
`)
  console.log(`[OpenFang] Created config at ${configPath}`)
}

// ── Daemon process ────────────────────────────────────────────────────────────
let daemonProc = null

function startDaemon(binPath) {
  if (daemonProc) return

  ensureConfig()
  setStatus('starting', `Starting OpenFang daemon on port ${OPENFANG_PORT}…`)

  // Pass the Anthropic API key from the project .env if available
  const env = {
    ...process.env,
    ANTHROPIC_API_KEY: process.env.ANTHROPIC_API_KEY ?? process.env.VITE_ANTHROPIC_API_KEY ?? '',
  }

  // OpenFang daemon command is `start` (not `daemon start`)
  daemonProc = spawn(binPath, ['start'], { stdio: 'pipe', env })

  daemonProc.on('error', (err) => {
    daemonProc = null
    const hint = err.code === 'EACCES' ? `Try: chmod +x ${binPath}` : ''
    setStatus('error', `Failed to start daemon: ${err.message}. ${hint}`)
  })

  daemonProc.stdout.on('data', (d) => {
    const line = d.toString().trim()
    if (line) console.log(`[OpenFang] ${line}`)
    // Don't set running yet — wait for health check + agent revive to complete
  })

  daemonProc.stderr.on('data', (d) => {
    const line = d.toString().trim()
    if (line) console.error(`[OpenFang] ${line}`)
  })

  daemonProc.on('exit', (code) => {
    daemonProc = null
    if (code !== 0 && code !== null) {
      setStatus('restarting', `Daemon exited (code ${code}) — restarting in 3s…`)
      setTimeout(() => startDaemon(binPath), 3000)
    } else {
      setStatus('stopped', 'Daemon stopped.')
    }
  })

  // Poll until healthy, then revive agents, then set running
  const startTime = Date.now()
  const pollUntilReady = async () => {
    const http = await import('http')

    const checkHealth = () => new Promise((resolve) => {
      const req = http.get(`http://127.0.0.1:${OPENFANG_PORT}/api/health`, (res) => {
        resolve(res.statusCode === 200)
      })
      req.on('error', () => resolve(false))
    })

    let isUp = false
    while (!isUp && (Date.now() - startTime) < 30000) {
      isUp = await checkHealth()
      if (!isUp) await new Promise(r => setTimeout(r, 1000))
    }

    if (isUp) {
      await reviveTerminatedAgents()
      setStatus('running', `OpenFang daemon running on port ${OPENFANG_PORT}`)
    } else {
      setStatus('error', `OpenFang daemon failed to start on port ${OPENFANG_PORT}`)
    }
  }
  setTimeout(pollUntilReady, 2000)
}

async function reviveTerminatedAgents() {
  try {
    const http = await import('http')
    const agents = await new Promise((resolve, reject) => {
      const req = http.get(`http://127.0.0.1:${OPENFANG_PORT}/api/agents`, (res) => {
        let data = ''
        res.on('data', d => { data += d })
        res.on('end', () => {
          try { resolve(JSON.parse(data)) } catch { resolve([]) }
        })
      })
      req.on('error', reject)
    })

    for (const agent of agents) {
      if (agent.state === 'Terminated' || !agent.ready) {
        console.log(`[OpenFang] Reviving terminated agent: ${agent.name} (${agent.id})`)
        await new Promise((resolve) => {
          const body = '{}'
          const req = http.request({
            hostname: '127.0.0.1', port: OPENFANG_PORT,
            path: `/api/agents/${agent.id}/restart`, method: 'POST',
            headers: { 'Content-Type': 'application/json', 'Content-Length': body.length },
          }, (res) => {
            res.on('data', () => {})
            res.on('end', resolve)
          })
          req.on('error', resolve)
          req.write(body)
          req.end()
        })
      }
    }
  } catch { /* daemon not ready yet — ignore */ }
}

// ── Download fallback (tries GitHub releases) ─────────────────────────────────

function tryDownload(url) {
  return new Promise((resolve, reject) => {
    mkdirSync(BIN_DIR, { recursive: true })
    const file = createWriteStream(BIN_PATH)
    function doGet(u) {
      httpsGet(u, (res) => {
        if (res.statusCode === 301 || res.statusCode === 302) { doGet(res.headers.location); return }
        if (res.statusCode !== 200) { file.close(); reject(new Error(`HTTP ${res.statusCode}`)); return }
        res.pipe(file)
        file.on('finish', () => {
          file.close()
          if (!IS_WIN) chmodSync(BIN_PATH, 0o755)
          resolve()
        })
      }).on('error', e => { file.close(); reject(e) })
    }
    doGet(url)
  })
}

async function tryAutoDownload() {
  const base = 'https://github.com/RightNow-AI/openfang/releases/latest/download'
  const candidates = IS_WIN
    ? [`${base}/openfang-windows-x64.exe`]
    : IS_MAC
    ? [`${base}/openfang-macos-${IS_ARM ? 'arm64' : 'x64'}`,
       `${base}/openfang-${IS_ARM ? 'aarch64' : 'x86_64'}-apple-darwin`]
    : [`${base}/openfang-linux-${IS_ARM ? 'arm64' : 'x64'}`,
       `${base}/openfang-${IS_ARM ? 'aarch64' : 'x86_64'}-unknown-linux-gnu`]

  for (const url of candidates) {
    try {
      setStatus('downloading', `Downloading OpenFang binary…`)
      await tryDownload(url)
      if (isValidBinary(BIN_PATH)) return true
      try { unlinkSync(BIN_PATH) } catch {}
    } catch { /* try next */ }
  }
  return false
}

// ── Manager HTTP API (status + configure) ────────────────────────────────────
let pendingBinPath = null  // set once binary is found, before daemon starts

function restartDaemonWithKey(apiKey, binPath) {
  if (daemonProc) {
    try { daemonProc.kill() } catch {}
    daemonProc = null
  }
  process.env.ANTHROPIC_API_KEY = apiKey

  // Wipe the agent database so OpenFang spawns a fresh agent instead of
  // restoring the old Terminated one (which causes 500 "Agent processing failed")
  const dataDir = path.join(os.homedir(), '.openfang', 'data')
  for (const f of ['openfang.db', 'openfang.db-wal', 'openfang.db-shm']) {
    try { unlinkSync(path.join(dataDir, f)) } catch { /* already gone */ }
  }

  // Write fresh config with current port
  const configDir  = path.join(os.homedir(), '.openfang')
  const configPath = path.join(configDir, 'config.toml')
  writeFileSync(configPath, `# OpenFang config — auto-generated by Agentis
api_listen = "127.0.0.1:${OPENFANG_PORT}"

[default_model]
provider = "anthropic"
model    = "claude-sonnet-4-20250514"
api_key_env = "ANTHROPIC_API_KEY"

[memory]
decay_rate = 0.05
`)
  setTimeout(() => startDaemon(binPath), 500)
}

const apiServer = createServer((req, res) => {
  res.setHeader('Access-Control-Allow-Origin', '*')
  res.setHeader('Access-Control-Allow-Methods', 'GET, POST, OPTIONS')
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type')

  if (req.method === 'OPTIONS') { res.writeHead(204); res.end(); return }

  if (req.method === 'POST' && req.url === '/configure') {
    let body = ''
    req.on('data', d => { body += d })
    req.on('end', () => {
      try {
        const { apiKey } = JSON.parse(body)
        if (apiKey && apiKey.startsWith('sk-')) {
          const bin = pendingBinPath ?? BIN_PATH
          console.log(`[OpenFang Manager] Received API key — (re)starting daemon`)
          restartDaemonWithKey(apiKey, bin)
          res.setHeader('Content-Type', 'application/json')
          res.end(JSON.stringify({ ok: true }))
        } else {
          res.writeHead(400); res.end(JSON.stringify({ error: 'Invalid API key' }))
        }
      } catch {
        res.writeHead(400); res.end(JSON.stringify({ error: 'Bad request' }))
      }
    })
    return
  }

  res.setHeader('Content-Type', 'application/json')
  res.end(JSON.stringify({ ...status, binPath: BIN_PATH }))
})
apiServer.on('error', (err) => {
  if (err.code === 'EADDRINUSE') {
    console.warn(`[OpenFang Manager] Port ${MANAGER_PORT} in use — another instance may be running.`)
  }
})
apiServer.listen(MANAGER_PORT, () =>
  console.log(`[OpenFang Manager] Status API → http://localhost:${MANAGER_PORT}`)
)

// ── Boot sequence ─────────────────────────────────────────────────────────────
function maybeStartOrWaitForKey(binPath) {
  const key = process.env.ANTHROPIC_API_KEY ?? process.env.VITE_ANTHROPIC_API_KEY ?? ''
  pendingBinPath = binPath
  if (key && key.startsWith('sk-')) {
    startDaemon(binPath)
  } else {
    setStatus('needs_api_key', 'API key required — enter it in Agentis to start the daemon.')
    console.log('[OpenFang] Waiting for API key via /configure endpoint…')
  }
}

;(async () => {
  // 1. Valid binary in ./bin/?
  if (existsSync(BIN_PATH) && isValidBinary(BIN_PATH)) {
    console.log(`[OpenFang] Binary found at ${BIN_PATH}`)
    maybeStartOrWaitForKey(BIN_PATH)
    return
  }
  if (existsSync(BIN_PATH)) {
    console.warn(`[OpenFang] Stale binary removed.`)
    try { unlinkSync(BIN_PATH) } catch {}
  }

  // 2. Fresh build output from cloned repo?
  if (existsSync(BUILD_OUT) && isValidBinary(BUILD_OUT)) {
    console.log(`[OpenFang] Using build output from ${BUILD_OUT}`)
    mkdirSync(BIN_DIR, { recursive: true })
    const { copyFileSync } = await import('fs')
    copyFileSync(BUILD_OUT, BIN_PATH)
    chmodSync(BIN_PATH, 0o755)
    maybeStartOrWaitForKey(BIN_PATH)
    return
  }

  // 3. Available in PATH?
  const pathBin = findInPath()
  if (pathBin && isValidBinary(pathBin)) {
    console.log(`[OpenFang] Found in PATH: ${pathBin}`)
    maybeStartOrWaitForKey(pathBin)
    return
  }

  // 4. Try GitHub release download
  setStatus('downloading', 'Looking for OpenFang release binary…')
  const downloaded = await tryAutoDownload()
  if (downloaded) {
    maybeStartOrWaitForKey(BIN_PATH)
    return
  }

  // 5. Build still in progress?
  if (existsSync('/tmp/openfang')) {
    setStatus('building',
      'Building OpenFang from source — this takes ~5 min on first run.\n' +
      'The daemon will start automatically once the build finishes.'
    )
    // Poll for build completion
    const poll = setInterval(async () => {
      if (existsSync(BUILD_OUT) && isValidBinary(BUILD_OUT)) {
        clearInterval(poll)
        const { copyFileSync } = await import('fs')
        mkdirSync(BIN_DIR, { recursive: true })
        copyFileSync(BUILD_OUT, BIN_PATH)
        chmodSync(BIN_PATH, 0o755)
        startDaemon(BIN_PATH)
      }
    }, 5000)
    return
  }

  // 6. Not installed at all
  setStatus('not_installed',
    'OpenFang binary not found. Build it once:\n' +
    `  git clone https://github.com/RightNow-AI/openfang /tmp/openfang\n` +
    `  cd /tmp/openfang && cargo build --release -p openfang-cli\n` +
    `  cp /tmp/openfang/target/release/openfang ${BIN_PATH}\n` +
    'Then restart Agentis.'
  )
})()

// ── Cleanup ───────────────────────────────────────────────────────────────────
function cleanup() {
  if (daemonProc) { try { daemonProc.kill() } catch {} }
  try { apiServer.close() } catch {}
}
process.on('exit', cleanup)
process.on('SIGINT',  () => { cleanup(); process.exit(0) })
process.on('SIGTERM', () => { cleanup(); process.exit(0) })
